/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package codificadorhuffman;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



/**
 *
 * @author Usuario
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Intro() {
        //setUndecorated(true);   
        //setOpacity(0.92f);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("imagenes/ico.png")));
           setLayout(new BorderLayout());
           
    JLabel background=new JLabel(new ImageIcon("LOGOTIPO_HARDCORE.jpg"));
    add(background);
    background.setLayout(new FlowLayout());
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ini = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CODIFICADOR HUFFMAN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ini.setBackground(new java.awt.Color(255, 51, 0));
        ini.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ini.setForeground(new java.awt.Color(255, 255, 255));
        ini.setText("START");
        ini.setBorder(null);
        ini.setFocusPainted(false);
        ini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniMouseExited(evt);
            }
        });
        ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniActionPerformed(evt);
            }
        });
        getContentPane().add(ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codificadorhuffman/imagenes/LOGOTIPO_HARDCORE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_iniMouseClicked

    private void iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniActionPerformed
        // TODO add your handling code here:
    ini.setBackground(new Color(204,51,0));
    principal gui=new principal();
    gui.setVisible(true);  
    this.dispose();
    }//GEN-LAST:event_iniActionPerformed

    private void iniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniMouseExited
        // TODO add your handling code here:
         ini.setText("START");
         ini.setBackground(new Color(255,51,0));
      
    }//GEN-LAST:event_iniMouseExited

    private void iniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniMouseEntered
        // TODO add your handling code here:
        ini.setText("START >");      
        ini.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_iniMouseEntered
  
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro().setVisible(true);
            }
        });
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ini;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
